# Generated by Django 4.0.4 on 2022-04-30 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_categoria', models.IntegerField(db_column='id_categoria')),
                ('nombre', models.CharField(db_column='nombre', max_length=50)),
                ('detalle', models.CharField(db_column='detalle', max_length=60)),
            ],
            options={
                'db_table': 'tbl_categoria',
            },
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id_cliente', models.AutoField(db_column='id_cliente', primary_key=True, serialize=False)),
                ('documento', models.CharField(db_column='documento', max_length=40)),
                ('cod_tipo_documento', models.CharField(db_column='cod_tipo_documento', max_length=40)),
                ('nombre', models.CharField(db_column='nombre', max_length=40)),
                ('apellido', models.CharField(db_column='apellido', max_length=40)),
                ('direccion', models.CharField(db_column='direccion', max_length=80)),
                ('telefono', models.CharField(db_column='telefono', max_length=12)),
                ('id_ciudad', models.IntegerField(db_column='id_cuidad')),
            ],
            options={
                'db_table': 'tbl_cliente',
            },
        ),
        migrations.CreateModel(
            name='detallefactura',
            fields=[
                ('id_detalleFactura', models.AutoField(db_column='id_detalle_factura', primary_key=True, serialize=False)),
                ('cod_factura', models.CharField(db_column='cod_factura', max_length=40)),
                ('cod_articulos', models.CharField(db_column='cod_articulos', max_length=40)),
                ('cantidad', models.IntegerField(db_column='cantidad')),
                ('total', models.DecimalField(db_column='total', decimal_places=2, max_digits=20)),
            ],
            options={
                'db_table': 'tbl_detallefactura',
            },
        ),
        migrations.CreateModel(
            name='devolucion',
            fields=[
                ('id_devolucion', models.AutoField(db_column='id_devolucion', primary_key=True, serialize=False)),
                ('id_detallefactura', models.IntegerField(db_column='id_detallefactura')),
                ('id_detalle_articulo', models.ImageField(db_column='id_detalle_articulo', upload_to='')),
                ('motivo', models.DecimalField(db_column='Monto', decimal_places=2, max_digits=20, null=True)),
                ('fecha_devolucion', models.DateField(db_column='fecha_devolucion')),
                ('cantidad', models.IntegerField(db_column='cantidad')),
            ],
            options={
                'db_table': 'tbl_devolucion',
            },
        ),
        migrations.CreateModel(
            name='factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('Nnm_factura', models.CharField(db_column='Nnm_factura', max_length=50)),
                ('cod_cliente', models.CharField(db_column='cod_cliente', max_length=50)),
                ('nombre_empleado', models.CharField(db_column='nombre_empleado', max_length=50)),
                ('fecha_factura', models.DateField(db_column='fecha_factura')),
                ('subtotal', models.DecimalField(db_column='subtotal', decimal_places=2, max_digits=20)),
                ('total_factura', models.DecimalField(db_column='total_factura', decimal_places=2, max_digits=20)),
                ('iva12', models.DecimalField(db_column='iva12%', decimal_places=2, max_digits=20)),
                ('iva0', models.DecimalField(db_column='iva0%', decimal_places=2, max_digits=20)),
                ('id_detalleFactura', models.ForeignKey(db_column='id_detalleFactura', on_delete=django.db.models.deletion.CASCADE, to='producto.detallefactura')),
            ],
            options={
                'db_table': 'tbl_factura',
            },
        ),
        migrations.CreateModel(
            name='formapago',
            fields=[
                ('id_formapago', models.AutoField(db_column='id_formapago', primary_key=True, serialize=False)),
                ('descripcion_fromapago', models.CharField(db_column='descripcion_fromapago', max_length=40)),
            ],
            options={
                'db_table': 'tbl_formapago',
            },
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id_proveedor', models.AutoField(db_column='id_proveedor', primary_key=True, serialize=False)),
                ('nombre_de_proveedor', models.CharField(db_column='nombre_de_proveedr', max_length=50)),
                ('telefono_provedor', models.CharField(db_column='telefono_provedor', max_length=50)),
                ('direccion', models.CharField(db_column='direccion', max_length=50)),
                ('email_proveedor', models.CharField(db_column='email_proveedor', max_length=60)),
            ],
            options={
                'db_table': 'tbl_proveedor',
            },
        ),
        migrations.CreateModel(
            name='tipo_articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tipoarticulo', models.IntegerField(db_column='id_tipo_articulos')),
                ('descripcion_articulo', models.CharField(db_column='descripcion_articulo', max_length=50)),
            ],
            options={
                'db_table': 'tbl_tipo_articulo',
            },
        ),
        migrations.CreateModel(
            name='tipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(db_column='Descripcion', max_length=80)),
                ('id_tipo_documento', models.ForeignKey(db_column='id_tipo_documento', on_delete=django.db.models.deletion.CASCADE, to='producto.cliente')),
            ],
            options={
                'db_table': 'tbl_tipoDocumento',
            },
        ),
        migrations.CreateModel(
            name='porducto',
            fields=[
                ('id_articlo', models.AutoField(db_column='id_articulo', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='descripcio', max_length=50)),
                ('precio_venta', models.DecimalField(db_column='precio_venta', decimal_places=2, max_digits=20, null=True)),
                ('precio_costo', models.DecimalField(db_column='precio_costo', decimal_places=2, max_digits=20, null=True)),
                ('stock', models.IntegerField(db_column='stock')),
                ('fecha_ingreso', models.DateField(db_column='fecha_ingreso')),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='producto.categoria')),
                ('id_devolucion', models.ForeignKey(db_column='id_devolucion', on_delete=django.db.models.deletion.CASCADE, to='producto.devolucion')),
                ('id_factura', models.ForeignKey(db_column='id_factura', on_delete=django.db.models.deletion.CASCADE, to='producto.factura')),
                ('id_proveedor', models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.CASCADE, to='producto.proveedor')),
                ('id_tipo_articulo', models.ForeignKey(db_column='cod_tipo_articulo', on_delete=django.db.models.deletion.CASCADE, to='producto.tipo_articulo')),
            ],
            options={
                'db_table': 'tbl_porducto',
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='id_forma_de_pago',
            field=models.ForeignKey(db_column='id_forma_de_pago', on_delete=django.db.models.deletion.CASCADE, to='producto.formapago'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_factura',
            field=models.ForeignKey(db_column='id_factura', on_delete=django.db.models.deletion.CASCADE, to='producto.factura'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_user',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.CreateModel(
            name='ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cuidad', models.CharField(db_column='nombre_cuidad', max_length=40)),
                ('id_codigo_cuidad', models.ForeignKey(db_column='id_codigo_cuidad', on_delete=django.db.models.deletion.CASCADE, to='producto.cliente')),
                ('id_proveedor', models.ForeignKey(db_column='id_porveedor', on_delete=django.db.models.deletion.CASCADE, to='producto.proveedor')),
            ],
            options={
                'db_table': 'tbl_ciudad',
            },
        ),
    ]
