# Generated by Django 4.0.4 on 2022-04-30 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(db_column='rol', max_length=50)),
                ('tipo_rol', models.IntegerField(db_column='tipo_rol')),
                ('idrol', models.ForeignKey(blank=True, db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'tbl_rol',
            },
        ),
    ]
